set nocompatible
let mapleader = "'"

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Bundle 'slim-template/vim-slim.git'
Bundle 'kchmck/vim-coffee-script'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-sensible'
Plugin 'majutsushi/tagbar'
Bundle 'mileszs/ack.vim'
Plugin 'rking/ag.vim'
Bundle 'tpope/vim-rails.git'
Bundle 'tpope/vim-rake.git'
Plugin 'vim-ruby/vim-ruby'
Plugin 'thoughtbot/vim-rspec'

Bundle 'kana/vim-vspec'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'

Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"
Bundle "honza/vim-snippets"
Bundle 'tcomment'
Bundle 'git://github.com/bling/vim-airline.git'
Bundle 'christoomey/vim-tmux-navigator'
Plugin 'fatih/vim-go'

call vundle#end()

filetype plugin indent on

syntax on
set history=10000
set nocompatible
set encoding=utf-8
set showcmd
set nu
set list
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set hlsearch
set incsearch
set autoindent
set ignorecase
set smartcase
set relativenumber
set updatecount=0
set cursorline
set cursorcolumn

hi CursorLine   cterm=NONE ctermbg=235
hi CursorColumn cterm=NONE ctermbg=235

" ctags -R --exclude=.git --exclude=log *
set tags=./tags;

colorscheme railscasts

" use the_silver_searcher for vim.ack
let g:ackprg = 'ag --nogroup --nocolor --column'

" set rspec runner for vim-rspec
let g:rspec_runner = "os_x_iterm"

" nerdtree shows hidden files in drawer
let NERDTreeShowHidden=1

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  let g:ctrlp_max_files = 0
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

map 'nt :NERDTree<CR>
map 'q :q<CR>
map 'b :b#<CR>
map 's :source ~/.vimrc<CR>
vmap 'b :<C-U>!git blame <C-R>=expand("%:p") <CR> \| sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>
nnoremap \c :set cursorline! cursorcolumn!<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <Leader>w :w<CR>
nnoremap <Leader><Leader> :CtrlP .<CR>
nnoremap <Leader>f /this_is_just_to_remove_the_search_results<CR>
nnoremap <Leader>h :sp<CR>
nnoremap <Leader>v :vs<CR>

nnoremap <Leader>t :call RunCurrentSpecFile()<CR>
nnoremap <Leader>s :call RunNearestSpec()<CR>
nnoremap <Leader>l :call RunLastSpec()<CR>
nnoremap <Leader>a :call RunAllSpecs()<CR>

iabbrev pry require 'pry'; binding.pry
